### ISSUE TITLE
Implement a genome import feature

### ISSUE THREAD

**Issue by lukasmueller** [opengenomebrowser/opengenomebrowser#6]
It would be nice to have a feature that would import genomes from genbank and other common sources using a web-based interface.

**Comment by MrTomRod** [comment]
It is now possible to import genomes via the web interface. See [documentation](https://opengenomebrowser.github.io/opengenomebrowser/admin/upload-genome.html).

The automatic download of files from sources like GenBank is still missing, though.

**Comment by MrTomRod** [comment]
Decided against "direct" GenBank import: Pure GenBank don't contain sufficient high-quality annotations for most OpenGenomeBrowser use cases. Usually, the genomes have to be downloaded and annotated ([eggNOG](https://github.com/eggnogdb/eggnog-mapper/wiki/) or similar). The annotation is too resource-intensive to run as a background job on a webserver.

Nevertheless, I simplified downloading GenBank genomes: see the [`download_ncbi_genome`](https://github.com/opengenomebrowser/opengenomebrowser-tools#download_ncbi_genome) script in `opengenomebrowser-tools`.
